### ISSUE TITLE
wordbook stucks at downloading WordNet due to en-word.net being down

### ISSUE THREAD

**Issue by kiayk** [fushinari/Wordbook#28]
* Wordbook version: 0.3.1 (flatpak)
* Python version: 3.8 according to flatpak output
* Operating System: fedora 34
* Desktop Enviroment: Gnome 40

### Description

wordbook stucks at **downloading WordNet** and gives `Connection to en-word.net timed out`. It's the only available offline dictionary on fedora repos. I would really appreciate it if you could provide another database.

### What I Did
I ran the app via flatpak cli, it refers to [en-word.net](http://en-word.net/) which is down and not working. The last Error is `wn.Error: Download failed at 0 bytes`. `Connection to en-word.net timed out.` I tried acssesing [en-word.net](http://en-word.net/) via browser and it seems not working anymore.
```
flatpak -v run com.github.fushinar.Wordbook

F: Running 'bwrap --args 41 xdg-dbus-proxy --args=43'
F: Running 'bwrap --args 41 wordbook'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/app/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/app/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/app/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/app/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/app/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/app/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f8ab85f64f0>, 'Connection to en-word.net timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/app/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='en-word.net', port=443): Max retries exceeded with url: /static/english-wordnet-2020.xml.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8ab85f64f0>, 'Connection to en-word.net timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/wn/_download.py", line 93, in _download
    with requests.get(url, stream=True, timeout=TIMEOUT) as response:
  File "/app/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/app/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/app/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='en-word.net', port=443): Max retries exceeded with url: /static/english-wordnet-2020.xml.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8ab85f64f0>, 'Connection to en-word.net timed out. (connect timeout=10)'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/wordbook/wordbook/base.py", line 404, in download
    wn.download("ewn:2020", progress_handler=progress_handler)
  File "/app/lib/python3.8/site-packages/wn/_download.py", line 72, in download
    _download(url, path, progress)
  File "/app/lib/python3.8/site-packages/wn/_download.py", line 103, in _download
    raise wn.Error(f'Download failed at {size} bytes') from exc
wn.Error: Download failed at 0 bytes

```

**Comment by cassop** [comment]
I think the website is back, consider closing this issue.

**Comment by fushinari** [comment]
Yep, the website is back. I'd forgotten about this issue :sweat_smile: Thanks for reminding me
